### ISSUE TITLE
Consider unforking this repository

### ISSUE THREAD

**Issue by jordanbtucker** [eslint-community/eslint-plugin-n#55]
This repository is currently forked from https://github.com/mysticatea/eslint-plugin-node, which makes it impossible to search code via GitHub. Since the original repository is stale, I'm not sure there is a point to keep it forked.

I recommend [unforking](https://stackoverflow.com/a/66470086) this repository to enable code search.

**Comment by voxpelli** [comment]
The current plan is to give some additional time to the original project owner to donate his project to this org.

After that time has passed I agree that this is what we should do.

**Comment by goosewobbler** [comment]
The original project owner couldn't be bothered to even respond once to anything regarding this project since abandoning it almost 3 years ago, despite being [chased around github](https://github.com/mysticatea/eslint-evaluating-issues/issues/4), but sure, let's wait another couple of years just in case, have to avoid hurting feelings 😅

**Comment by goosewobbler** [comment]
> The JavaScript community has benefited greatly from @mysticatea's work over the years. His work is extremely high quality & technical and he's been a reliable and respectable maintainer for many open source projects. I don't think anyone working hard to improve the ecosystem deserves that kind of treatment. Let's try to be more respectful and empathetic.

Fair enough, and I see the ridiculous number of repos on @mysticatea's account.  But anyone simply trying to use the library does not have this context.

> I don't want to pry, but everyone has a life outside of open source and you never know what circumstances they're dealing with.

Absolutely, and yet, if I started a popular repo and had to quickly leave github and social media, I would at least hand it over to someone (anyone) else. If there was not enough time to consider that then I would expect (and hope) for my project to be forked and then started anew as soon as possible.  If only so that I would not have to consider dealing with it again or having people trying to contact me.

> I would move on with unforking, and just hope he comes back one day. 🤞

This was my original point. The original repo is just really out of date.  If he comes back and wants to be involved again, I'm sure the current owner will let him be reinstated as project owner of this new project.

**Comment by voxpelli** [comment]
> let's wait another couple of years just in case, have to avoid hurting feelings 😅

Skip the sarcasm 🙏 

We want to follow due process as eg. outlined [in the RFC](https://github.com/eslint/rfcs/tree/main/designs/2022-community-eslint-org) and be open to maintainers about our intent before we make a final decision.

Now it has been more than 30, even more than 60, days and yeah, we should move forward with this

**Comment by voxpelli** [comment]
@MichaelDeBoey Do you want to do this for all of the projects? Else I go ahead and ask for this + https://github.com/eslint-community/regexpp/issues/33 + maybe the rest of the ones forked from the same maintainer? https://github.com/eslint-community?type=fork

**Comment by MichaelDeBoey** [comment]
@voxpelli I don't see any harm in keeping the fork status tbh as it's clearly a fork of the original one 🤷‍♂️
Are there any specific things we currently can't do because it's still a fork?

Keeping the fork also keeps the extra link on the original repo + people coming by this repo can see that it's a **maintained** fork instead of a new repo with about the same name

**Comment by jordanbtucker** [comment]
Keeping the fork makes it impossible to search the code in the repo on GitHub, unless they've fixed that recently.

**Comment by MichaelDeBoey** [comment]
@jordanbtucker Can you give some examples of what you're trying to look for?
All the things I just tested, just seem to work

**Comment by jordanbtucker** [comment]
Seems like search is working for forked repos now. At least for this repo. GitHub must have fixed that since I opened this issue. That was the only reason, so I don't mind closing this issue.
