### ISSUE TITLE
feat: support the new eslint config.

### ISSUE THREAD

**Issue by aladdin-add** [eslint-community/eslint-plugin-n#89]
eslint has introduced a new format config(`eslint.config.js`): https://eslint.org/docs/latest/use/configure/configuration-files-new

ideally, we could support both formats: eslintrc/flat.

**Comment by aladdin-add** [comment]
I'm preparing the v16 release, and I have merged a few breaking changes that dropped node.js < 16 supports.

Do you think it's worthy to port this to v15, so that it can be used in eslint repo (as of now it support node v12)? @mdjermanovic

**Comment by mdjermanovic** [comment]
> Preparing the v16 release, and I have merged a few breaking changes that dropped node.js < 16 supports.
> 
> Do you think it's worth porting this to v15, so that it can be used in eslint repo (as of now it supports node v12)? @mdjermanovic

I think it isn't necessary to port this to v15. CI linting in the eslint repo runs on Node 18 so that will be okay. We don't have official requirements for local development environments but I think it's reasonable to assume that a non-eol version of Node.js should be used. I believe we're already using some scripts and dev dependencies that don't work in all Node.js versions that eslint supports.
